import com.itextpdf.text.Paragraph;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.*;
import Project.Select;
import Project.InsertUpdateDelete;
import javax.swing.table.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Utari Dyani
 */
public class CheckOut extends javax.swing.JFrame {

    /**
     * Creates new form CheckOut
     */
    public CheckOut() {
        initComponents();
        
        CheckInDate.setEditable(false);
        RoomPrice.setEditable(false);
        CustomerName.setEditable(false);
        TotalAmount.setEditable(false);
        CheckOutDate.setEditable(false);
        NumberOfDays.setEditable(false);
    }
    
    int id=0;
    String Query;
    String roomType;
    String bedType;
    String roomNum;
    
    
    //Method Untuk Validasi Inputan User Berupa Angka
    public void filterAngka (KeyEvent b){
        if(Character.isAlphabetic(b.getKeyChar())){
            b.consume();
            //Tampilan peringatan jika user memasukkan karakter yang bukan angka
            JOptionPane.showMessageDialog(null, "Numeric Input Only!", "Warning!", JOptionPane.WARNING_MESSAGE);       
        }
    }
    
    //method untuk memfilter spasi
    public void filterSpace (KeyEvent c){
        if(Character.isWhitespace(c.getKeyChar())){
            c.consume();
            //Tampilan peringatan jika user menginputkan spasi
            JOptionPane.showMessageDialog(null, "No Spacing!", "Warning!", JOptionPane.WARNING_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        RoomPrice = new javax.swing.JTextField();
        CheckInDate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RoomNumber = new javax.swing.JTextField();
        NumberOfDays = new javax.swing.JTextField();
        CheckOutDate = new javax.swing.JTextField();
        TotalAmount = new javax.swing.JTextField();
        CustomerName = new javax.swing.JTextField();
        backButton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1366, 786));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(229, 155, 132));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(229, 155, 132)));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(229, 155, 132));
        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Full Name", "Phone Number", "Nationality", "Gender", "ID Proof", "Address", "CheckIn", "RoomNo", "Bed Type", "Room Type", "Price"
            }
        ));
        jTable1.setToolTipText("");
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setSelectionBackground(new java.awt.Color(229, 155, 132));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 1230, 280));

        RoomPrice.setBackground(new java.awt.Color(196, 196, 196));
        RoomPrice.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        RoomPrice.setBorder(null);
        getContentPane().add(RoomPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 350, 40));

        CheckInDate.setBackground(new java.awt.Color(196, 196, 196));
        CheckInDate.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        CheckInDate.setBorder(null);
        getContentPane().add(CheckInDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 350, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/CheckOut Button.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1082, 150, 210, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/SearchCheckOutButton.png"))); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(120, 62));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 120, 60));

        RoomNumber.setBackground(new java.awt.Color(229, 155, 132));
        RoomNumber.setFont(new java.awt.Font("Segoe UI Historic", 0, 36)); // NOI18N
        RoomNumber.setForeground(new java.awt.Color(255, 255, 255));
        RoomNumber.setBorder(null);
        RoomNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RoomNumberKeyTyped(evt);
            }
        });
        getContentPane().add(RoomNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 290, 40));

        NumberOfDays.setBackground(new java.awt.Color(196, 196, 196));
        NumberOfDays.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        NumberOfDays.setBorder(null);
        getContentPane().add(NumberOfDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 350, 40));

        CheckOutDate.setBackground(new java.awt.Color(196, 196, 196));
        CheckOutDate.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        CheckOutDate.setBorder(null);
        getContentPane().add(CheckOutDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 250, 350, 40));

        TotalAmount.setBackground(new java.awt.Color(196, 196, 196));
        TotalAmount.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        TotalAmount.setBorder(null);
        getContentPane().add(TotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 320, 350, 40));

        CustomerName.setBackground(new java.awt.Color(196, 196, 196));
        CustomerName.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        CustomerName.setBorder(null);
        getContentPane().add(CustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 350, 40));

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/CheckIn_BackButton.png"))); // NOI18N
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backButtonMouseExited(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1335, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/CheckOut Layout.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setBounds(0, 0, 1373, 803);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setExtendedState(CheckIn.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        ResultSet rs=Select.getData("select*from customer where checkOut is NULL");
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        try
        {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12)});
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        } 
    }//GEN-LAST:event_formComponentShown

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        String fullName=CustomerName.getText();
        String roomPrice=RoomPrice.getText();
        String checkInDate=CheckInDate.getText();
        String numberOfDays=NumberOfDays.getText();
        String checkOutDate=CheckOutDate.getText();
        String totalAmount=TotalAmount.getText();
        
        roomNum = RoomNumber.getText();
        Query="update customer set numberOfDays='"+numberOfDays+"', totalAmount='"+totalAmount+"', checkOut='"+checkOutDate+"' where id='"+id+"'";
        
        InsertUpdateDelete.setData(Query,"");
        Query="update room set Status = 'Available' where roomNumber='"+roomNum+"'";
        InsertUpdateDelete.setData(Query,"");
        String path="D:\\";
        com.itextpdf.text.Document doc= new com.itextpdf.text.Document();
        try
        {
           PdfWriter.getInstance(doc, new FileOutputStream(path+""+id+".pdf"));
           doc.open();
           
           Paragraph paragraph1= new Paragraph("+================================================================================================================================================+\n");
           doc.add(paragraph1);
           Paragraph paragraph2= new Paragraph("+------------------------------------------------------------------------------------------------------------------------------------------------+\n");
           doc.add(paragraph2);
           Paragraph paragraph3= new Paragraph("+                                                               HALLAVA'S BILLING                                                                +\n");
           doc.add(paragraph3);
           Paragraph paragraph4= new Paragraph("+------------------------------------------------------------------------------------------------------------------------------------------------+\n");
           doc.add(paragraph4);
           Paragraph paragraph5= new Paragraph("+================================================================================================================================================+\n");
           doc.add(paragraph5); 
           Paragraph paragraph6= new Paragraph("ID : "+id+"\n");
           doc.add(paragraph6);
           Paragraph paragraph7= new Paragraph("Name : "+fullName+"\n\n");
           doc.add(paragraph7);
           Paragraph paragraph8= new Paragraph("+-----------------------------------------------------------------------------------------------------------------------------------------------+\n");
           doc.add(paragraph8);
           Paragraph paragraph9= new Paragraph("Room Number : "+roomNum+"\n");
           doc.add(paragraph9);
           Paragraph paragraph10= new Paragraph("Room Price : "+roomPrice+"\n\n");
           doc.add(paragraph10);
           Paragraph paragraph11= new Paragraph("+---------------------------------------------------------------------------------------------------------------------------------------------+\n");
           doc.add(paragraph11);
           Paragraph paragraph12= new Paragraph("Check In Date : "+checkInDate+"\n");
           doc.add(paragraph12);
           Paragraph paragraph13= new Paragraph("Check Out Date : "+checkOutDate+"\n");
           doc.add(paragraph13);
           Paragraph paragraph14= new Paragraph("Number Of Days : "+numberOfDays+"\n");
           doc.add(paragraph14);
           Paragraph paragraph15= new Paragraph("Total Amount : "+totalAmount+"\n");
           doc.add(paragraph15);
           Paragraph paragraph16= new Paragraph("+============================================================================================================================================+\n");
           doc.add(paragraph16);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        doc.close();
        int a=JOptionPane.showConfirmDialog(null, "Do You Want To Print The Bill?", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            try
            {
                if((new File("D:\\"+id+".pdf")).exists())
                {
                    Process p =Runtime
                            .getRuntime()
                            .exec("rundll32 url.dll,FileProtocolHandler D:\\"+id+".pdf");                           
                }
                else
                    System.out.println("File Not Found");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        setVisible(false);
        new CheckOut().setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void RoomNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RoomNumberKeyTyped
        filterAngka(evt);
        filterSpace(evt);
    }//GEN-LAST:event_RoomNumberKeyTyped

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        String roomNo = RoomNumber.getText();
        try
        {
            ResultSet rs=Select.getData("select *from customer where roomNo='"+roomNo+"' and checkOut is null");
            if(rs.next())
            {
                id=rs.getInt(1);
                CustomerName.setText(rs.getString(2));
                RoomPrice.setText(rs.getString(12));
                CheckInDate.setText(rs.getString(8));

                SimpleDateFormat myFormat= new SimpleDateFormat("dd/MM/yyyy");
                Calendar cal=Calendar.getInstance();

                CheckOutDate.setText(myFormat.format(cal.getTime()));
                String dateBeforeString=rs.getString(8);
                java.util.Date dateBefore=myFormat.parse(dateBeforeString);
                String dateAfterString=myFormat.format(cal.getTime());
                java.util.Date dateAfter=myFormat.parse(dateAfterString);

                //menghitung hari customer tinggal di hotel
                long difference=dateAfter.getTime() - dateBefore.getTime();
                int noOfDays = (int)(difference/(1000*60*60*24));
                if(noOfDays == 0)
                noOfDays=1;
                NumberOfDays.setText(String.valueOf(noOfDays));

                //menghitung harga keseluruhan yang harus dibayar
                int price = Integer.parseInt(RoomPrice.getText());
                TotalAmount.setText(String.valueOf(noOfDays*price));
                roomType=rs.getString(11);
                bedType=rs.getString(10);
            }
            else
            JOptionPane.showMessageDialog(null, "No Room Detected");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jLabel7MouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        dispose();
        Menu menu = new Menu();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
    }//GEN-LAST:event_backButtonMouseClicked

    private void backButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseEntered
        // TODO add your handling code here:
        Border IconBorder = BorderFactory.createMatteBorder(1,1,1,1, new Color(255, 225, 255));
        backButton.setBorder(IconBorder);
        backButton.setForeground(new Color(255, 225, 255));
    }//GEN-LAST:event_backButtonMouseEntered

    private void backButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseExited
        // TODO add your handling code here:
        Border IconBorder = BorderFactory.createMatteBorder(0,0,0,0, Color.white);
        backButton.setBorder(IconBorder);
        backButton.setForeground(Color.white);
    }//GEN-LAST:event_backButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CheckInDate;
    private javax.swing.JTextField CheckOutDate;
    private javax.swing.JTextField CustomerName;
    private javax.swing.JTextField NumberOfDays;
    private javax.swing.JTextField RoomNumber;
    private javax.swing.JTextField RoomPrice;
    private javax.swing.JTextField TotalAmount;
    private javax.swing.JLabel backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
