
import com.itextpdf.text.Paragraph;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.*;
import connect.*;
import javax.swing.table.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Utari Dyani
 */
public class CheckOut extends javax.swing.JFrame {

    /**
     * Creates new form CheckOut
     */
    public CheckOut() {
        initComponents();
        
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
    }
    
    int id=0;
    String Query;
    String roomType;
    String bedType;
    String roomNumber;
    
    
    //Method Untuk Validasi Inputan User Berupa Angka
    public void filterAngka (KeyEvent b){
        if(Character.isAlphabetic(b.getKeyChar())){
            b.consume();
            //Tampilan peringatan jika user memasukkan karakter yang bukan angka
            JOptionPane.showMessageDialog(null, "Masukkan Data dalam Format Angka!", "Warning!", JOptionPane.WARNING_MESSAGE);       
        }
    }
    
    //method untuk memfilter spasi
    public void filterSpace (KeyEvent c){
        if(Character.isWhitespace(c.getKeyChar())){
            c.consume();
            //Tampilan peringatan jika user menginputkan spasi
            JOptionPane.showMessageDialog(null, "Dilarang Menggunakan Spasi", "Warning!", JOptionPane.WARNING_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1366, 786));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Segoe UI Historic", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Full Name", "Phone No", "Nationality", "Gender", "ID Proof", "Address", "CheckIn", "RoomNo", "Bed Type", "Room Type", "SmokingR", "Price"
            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 1230, 280));

        jTextField2.setBackground(new java.awt.Color(196, 196, 196));
        jTextField2.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 360, 40));

        jTextField1.setBackground(new java.awt.Color(196, 196, 196));
        jTextField1.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 360, 40));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_checkout/Check Out Date.png"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 220, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_checkout/Number of Days.png"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_checkout/Check In Date.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_checkout/Room Price.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_checkout/Customer Name.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_checkout/Total Price.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 300, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_checkout/check out_checkout.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 140, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_checkout/Room Number text_checkout.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_checkout/Customer Info_checkout.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 376, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_checkout/custinfo_layout.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_checkout/heading (1).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 30, -1, -1));

        jTextField7.setBackground(new java.awt.Color(229, 155, 132));
        jTextField7.setFont(new java.awt.Font("Segoe UI Historic", 0, 36)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 145, 190, 40));

        jTextField6.setBackground(new java.awt.Color(196, 196, 196));
        jTextField6.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 360, 40));

        jTextField5.setBackground(new java.awt.Color(196, 196, 196));
        jTextField5.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 240, 360, 40));

        jTextField4.setBackground(new java.awt.Color(196, 196, 196));
        jTextField4.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 320, 360, 40));

        jTextField3.setBackground(new java.awt.Color(196, 196, 196));
        jTextField3.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 360, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_checkout/search_checkout.png"))); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(120, 62));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 145, 130, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_checkout/backbutton_checkout.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1333, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_checkout/base_checkout.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setBounds(0, 0, 1389, 842);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setExtendedState(CheckIn.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        ResultSet rs=Select.getData("select*from customer where checkOutDate is NULL");
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        try
        {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12),rs.getString(13)});
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        } 
    }//GEN-LAST:event_formComponentShown

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        String roomNo = jTextField7.getText();
        try
        {
            ResultSet rs=Select.getData("select *from customer where roomNo='"+roomNo+"' and checkOutDate is null");
            if(rs.next())
            {
                id=rs.getInt(1);
                jTextField3.setText(rs.getString(2));
                jTextField2.setText(rs.getString(13));
                jTextField1.setText(rs.getString(8));
                
                SimpleDateFormat myFormat= new SimpleDateFormat("dd/MM/yyyy");
                Calendar cal=Calendar.getInstance();
                
                jTextField5.setText(myFormat.format(cal.getTime()));
                String dateBeforeString=rs.getString(8);
                java.util.Date dateBefore=myFormat.parse(dateBeforeString);
                String dateAfterString=myFormat.format(cal.getTime());
                java.util.Date dateAfter=myFormat.parse(dateAfterString);
                
                //menghitung hari customer tinggal di hotel
                long difference=dateAfter.getTime() - dateBefore.getTime();
                int noOfDays = (int)(difference/(1000*60*60*24));
                if(noOfDays == 0)
                    noOfDays=1;
                jTextField6.setText(String.valueOf(noOfDays));
                
                //menghitung harga keseluruhan yang harus dibayar
                float price = Float.parseFloat(jTextField2.getText());
                jTextField4.setText(String.valueOf(noOfDays*price));
            }
            else
                JOptionPane.showMessageDialog(null, "No Room Detected");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        String fullName=jTextField3.getText();
        String roomPrice=jTextField2.getText();
        String checkInDate=jTextField1.getText();
        String numberOfDays=jTextField6.getText();
        String checkOutDate=jTextField5.getText();
        String totalPrice=jTextField4.getText();
        
        roomNumber = jTextField7.getText();
        Query="update customer set numberOfDays='"+numberOfDays+"', totalPrice='"+totalPrice+"', checkOutDate='"+checkOutDate+"' where id='"+id+"'";
        
        InsertUpdateDelete.setData(Query,"");
        Query="update tb_room set roomStatus='Available' where roomNumber='"+roomNumber+"'";
        
        InsertUpdateDelete.setData(Query,"");
        String path="D:\\";
        com.itextpdf.text.Document doc= new com.itextpdf.text.Document();
        try
        {
           PdfWriter .getInstance(doc, new FileOutputStream(path+""+id+".pdf"));
           doc.open();
           
           Paragraph paragraph1= new Paragraph("+================================================================================================================================================+\n");
           doc.add(paragraph1);
           Paragraph paragraph2= new Paragraph("+------------------------------------------------------------------------------------------------------------------------------------------------+\n");
           doc.add(paragraph2);
           Paragraph paragraph3= new Paragraph("+                                                               HALLAVA'S BILLING                                                                +\n");
           doc.add(paragraph3);
           Paragraph paragraph4= new Paragraph("+------------------------------------------------------------------------------------------------------------------------------------------------+\n");
           doc.add(paragraph4);
           Paragraph paragraph5= new Paragraph("+================================================================================================================================================+\n");
           doc.add(paragraph5); 
           Paragraph paragraph6= new Paragraph("ID : "+id+"\n");
           doc.add(paragraph6);
           Paragraph paragraph7= new Paragraph("Name : "+fullName+"\n\n");
           doc.add(paragraph7);
           Paragraph paragraph8= new Paragraph("+-------------------------------------------------------------------------------------------------------------------------------------------------+\n");
           doc.add(paragraph8);
           Paragraph paragraph9= new Paragraph("Room Number : "+roomNumber+"\n");
           doc.add(paragraph9);
           Paragraph paragraph10= new Paragraph("Room Price : "+roomPrice+"\n\n");
           doc.add(paragraph10);
           Paragraph paragraph11= new Paragraph("+------------------------------------------------------------------------------------------------------------------------------------------------+\n");
           doc.add(paragraph11);
           Paragraph paragraph12= new Paragraph("Check In Date : "+checkInDate+"\n");
           doc.add(paragraph12);
           Paragraph paragraph13= new Paragraph("Check Out Date : "+checkOutDate+"\n");
           doc.add(paragraph13);
           Paragraph paragraph14= new Paragraph("Number Of Days : "+numberOfDays+"\n");
           doc.add(paragraph14);
           Paragraph paragraph15= new Paragraph("Total Price : "+totalPrice+"\n");
           doc.add(paragraph15);
           Paragraph paragraph16= new Paragraph("+================================================================================================================================================+\n");
           doc.add(paragraph16);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        doc.close();
        int a=JOptionPane.showConfirmDialog(null, "Do You Want To Print The Bill?", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            try
            {
                if((new File("D:\\"+id+".pdf")).exists())
                {
                    Process p=Runtime
                            .getRuntime()
                            .exec("rundll32 url.dll.FileProtocolHandler D:\\"+id+".pdf");                           
                }
                else
                    System.out.println("File Not Found");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        setVisible(false);
        new CheckOut().setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        filterAngka(evt);
        filterSpace(evt);
    }//GEN-LAST:event_jTextField7KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
