
import java.awt.Color;
import java.awt.Font;
import java.awt.event.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import java.sql.*;
import connect.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Utari Dyani
 */
public class CheckIn extends javax.swing.JFrame {

    /**
     * Creates new form CheckIn
     */
    public CheckIn() {
        initComponents();
        
        //mengatur tanggal check in menjadi tanggal hari ini
        dateField.setEditable(false);
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        Calendar cal = Calendar.getInstance();
        dateField.setText(format.format(cal.getTime()));
        dateField.setFont(new Font("Segoe UI Historic", Font.PLAIN, 30));
    }
    
    //deklarasi objek
    String bed;
    String roomType;
    String roomNo;
    String price;
    String smokingRoom;
    
    public void roomDetails(){
        roomNumberField.removeAllItems();
        priceField.setText("");
        bed = (String)bedTypeField.getSelectedItem();
        roomType = (String)roomTypeField.getSelectedItem();
        smokingRoom = (String)smokingRoomField.getSelectedItem();
        
        try
        {
            ResultSet rs = Select.getData("select *from tb_room where bed = '"+bed+"' and roomType='"+roomType+"' and smokingRoom='"+smokingRoom+"'");
            while(rs.next())
            {
                roomNumberField.addItem(rs.getString(1));
                priceField.setText(rs.getString(5));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    //Method untuk Memfilter Kolom hanya Bisa Diisi Huruf
    public void filterHuruf(KeyEvent a){
        if(Character.isDigit(a.getKeyChar())){
            a.consume();
            //Tampilan peringatan jika user memasukkan data berupa angka
            JOptionPane.showMessageDialog(null, "Hanya Inputkan Huruf!", "Warning!", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    //Method Untuk Validasi Inputan User Berupa Angka
    public void filterAngka (KeyEvent b){
        if(Character.isAlphabetic(b.getKeyChar())){
            b.consume();
            //Tampilan peringatan jika user memasukkan karakter yang bukan angka
            JOptionPane.showMessageDialog(null, "Masukkan Data dalam Format Angka!", "Warning!", JOptionPane.WARNING_MESSAGE);       
        }
    }
    
    //method untuk memfilter spasi
    public void filterSpace (KeyEvent c){
        if(Character.isWhitespace(c.getKeyChar())){
            c.consume();
            //Tampilan peringatan jika user menginputkan spasi
            JOptionPane.showMessageDialog(null, "Dilarang Menggunakan Spasi", "Warning!", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gender = new javax.swing.JComboBox<>();
        roomTypeField = new javax.swing.JComboBox<>();
        smokingRoomField = new javax.swing.JComboBox<>();
        Nationality = new javax.swing.JComboBox<>();
        bedTypeField = new javax.swing.JComboBox<>();
        priceField = new javax.swing.JTextField();
        roomNumberField = new javax.swing.JComboBox<>();
        dateField = new javax.swing.JTextField();
        IDProofField = new javax.swing.JTextField();
        phoneNumberField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        fullNameField = new javax.swing.JTextField();
        checkInButton = new javax.swing.JLabel();
        backButton = new javax.swing.JLabel();
        roomLayout = new javax.swing.JLabel();
        identityLayout = new javax.swing.JLabel();
        dateLayout = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        baseLayout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Gender.setBackground(new java.awt.Color(242, 218, 218));
        Gender.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        Gender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 218, 218), 7));
        getContentPane().add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 300, 50));

        roomTypeField.setBackground(new java.awt.Color(242, 218, 218));
        roomTypeField.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        roomTypeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "Non-AC" }));
        roomTypeField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 218, 218), 5));
        roomTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomTypeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(roomTypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 310, 390, 40));

        smokingRoomField.setBackground(new java.awt.Color(242, 218, 218));
        smokingRoomField.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        smokingRoomField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        smokingRoomField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 218, 218), 5));
        smokingRoomField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smokingRoomFieldActionPerformed(evt);
            }
        });
        getContentPane().add(smokingRoomField, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 390, 40));

        Nationality.setBackground(new java.awt.Color(242, 218, 218));
        Nationality.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        Nationality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indonesia", "Malaysia", "Singapura", "Thailand", "Brunei" }));
        Nationality.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 218, 218), 7));
        getContentPane().add(Nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 300, 50));

        bedTypeField.setBackground(new java.awt.Color(242, 218, 218));
        bedTypeField.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        bedTypeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double" }));
        bedTypeField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 218, 218), 5));
        bedTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bedTypeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(bedTypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, 390, 40));

        priceField.setBackground(new java.awt.Color(242, 218, 218));
        priceField.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        getContentPane().add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 570, 390, 40));

        roomNumberField.setBackground(new java.awt.Color(242, 218, 218));
        roomNumberField.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        roomNumberField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "001", "002", "003", "004", "005", "006", "007", "008", "009", "010", "011", "012", "013", "014", "015" }));
        roomNumberField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 218, 218), 5));
        roomNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNumberFieldActionPerformed(evt);
            }
        });
        getContentPane().add(roomNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 480, 390, 40));

        dateField.setBackground(new java.awt.Color(242, 218, 218));
        dateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFieldActionPerformed(evt);
            }
        });
        getContentPane().add(dateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 610, 440, 70));

        IDProofField.setBackground(new java.awt.Color(242, 218, 218));
        IDProofField.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        IDProofField.setForeground(new java.awt.Color(102, 102, 102));
        IDProofField.setText("   ID Proof");
        IDProofField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IDProofFieldMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IDProofFieldMouseExited(evt);
            }
        });
        IDProofField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IDProofFieldKeyTyped(evt);
            }
        });
        getContentPane().add(IDProofField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 610, 40));

        phoneNumberField.setBackground(new java.awt.Color(242, 218, 218));
        phoneNumberField.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        phoneNumberField.setForeground(new java.awt.Color(102, 102, 102));
        phoneNumberField.setText("   Phone Number");
        phoneNumberField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoneNumberFieldMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                phoneNumberFieldMouseExited(evt);
            }
        });
        phoneNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNumberFieldKeyTyped(evt);
            }
        });
        getContentPane().add(phoneNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 610, 40));

        addressField.setBackground(new java.awt.Color(242, 218, 218));
        addressField.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        addressField.setForeground(new java.awt.Color(102, 102, 102));
        addressField.setText("   Address");
        addressField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressFieldMouseClicked(evt);
            }
        });
        getContentPane().add(addressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 610, 40));

        fullNameField.setBackground(new java.awt.Color(242, 218, 218));
        fullNameField.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        fullNameField.setForeground(new java.awt.Color(102, 102, 102));
        fullNameField.setText("   Full Name");
        fullNameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fullNameFieldMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fullNameFieldMouseExited(evt);
            }
        });
        fullNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fullNameFieldKeyTyped(evt);
            }
        });
        getContentPane().add(fullNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 610, 40));

        checkInButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\Frame 2.png")); // NOI18N
        checkInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkInButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkInButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                checkInButtonMouseExited(evt);
            }
        });
        getContentPane().add(checkInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 640, -1, -1));

        backButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\back.png")); // NOI18N
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1335, 0, -1, -1));

        roomLayout.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\room.png")); // NOI18N
        getContentPane().add(roomLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 155, -1, -1));

        identityLayout.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\identity (1).png")); // NOI18N
        identityLayout.setAlignmentY(0.0F);
        getContentPane().add(identityLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 155, -1, -1));

        dateLayout.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\date.png")); // NOI18N
        getContentPane().add(dateLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 550, -1, -1));

        header.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\heading.png")); // NOI18N
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 30, -1, -1));

        baseLayout.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\base.png")); // NOI18N
        getContentPane().add(baseLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setBounds(0, 0, 1388, 824);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setExtendedState(CheckIn.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void fullNameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullNameFieldMouseClicked
        fullNameField.setText("");
        fullNameField.setForeground(Color.BLACK);
    }//GEN-LAST:event_fullNameFieldMouseClicked

    private void fullNameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fullNameFieldKeyTyped
        filterHuruf(evt);
    }//GEN-LAST:event_fullNameFieldKeyTyped

    private void fullNameFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullNameFieldMouseExited

    }//GEN-LAST:event_fullNameFieldMouseExited

    private void IDProofFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDProofFieldMouseClicked
        IDProofField.setText("");
        IDProofField.setForeground(Color.BLACK);
    }//GEN-LAST:event_IDProofFieldMouseClicked

    private void IDProofFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDProofFieldMouseExited

    }//GEN-LAST:event_IDProofFieldMouseExited

    private void IDProofFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDProofFieldKeyTyped
        filterAngka(evt);
        filterSpace(evt);
    }//GEN-LAST:event_IDProofFieldKeyTyped

    private void phoneNumberFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneNumberFieldMouseClicked
        phoneNumberField.setText("");
        phoneNumberField.setForeground(Color.BLACK);
    }//GEN-LAST:event_phoneNumberFieldMouseClicked

    private void phoneNumberFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneNumberFieldMouseExited

    }//GEN-LAST:event_phoneNumberFieldMouseExited

    private void phoneNumberFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumberFieldKeyTyped
        filterAngka(evt);
        filterSpace(evt);
    }//GEN-LAST:event_phoneNumberFieldKeyTyped

    private void addressFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressFieldMouseClicked
        addressField.setText("");
        addressField.setForeground(Color.BLACK);
    }//GEN-LAST:event_addressFieldMouseClicked

    private void dateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFieldActionPerformed

    }//GEN-LAST:event_dateFieldActionPerformed

    private void bedTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bedTypeFieldActionPerformed
        roomDetails();
    }//GEN-LAST:event_bedTypeFieldActionPerformed

    private void roomTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomTypeFieldActionPerformed
        roomDetails();
    }//GEN-LAST:event_roomTypeFieldActionPerformed

    private void smokingRoomFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smokingRoomFieldActionPerformed
        roomDetails();
    }//GEN-LAST:event_smokingRoomFieldActionPerformed

    private void roomNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNumberFieldActionPerformed

    }//GEN-LAST:event_roomNumberFieldActionPerformed

    private void checkInButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkInButtonMouseEntered
        checkInButton.setSize(135, 42);
    }//GEN-LAST:event_checkInButtonMouseEntered

    private void checkInButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkInButtonMouseExited
        checkInButton.setSize(131, 38);
    }//GEN-LAST:event_checkInButtonMouseExited

    private void checkInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkInButtonMouseClicked
        int id = 1;
        String name = fullNameField.getText();
        String idProof = IDProofField.getText();
        String phoneNumber = phoneNumberField.getText();
        String address = addressField.getText();
        String nationality =(String)Nationality.getSelectedItem();
        String gender = (String)Gender.getSelectedItem();
        String date = dateField.getText();
        String bedType = (String)bedTypeField.getSelectedItem();
        String room = (String)roomTypeField.getSelectedItem();
        String smoking = (String)smokingRoomField.getSelectedItem();
        String roomNumber = (String)roomNumberField.getSelectedItem();
        String roomPrice = priceField.getText();
        String Query = "select max(id) from customer";
        try
        {
            ResultSet rs = Select.getData(Query);
            while(rs.next())
                id=rs.getInt(1);
            id=id+1;
            
            if(!roomPrice.equals(""))
            {
                Query = "update tb_room set roomStatus = 'Booked' where roomNumber = '"+roomNumber+"'";
                InsertUpdateDelete.setData(Query, "");
                Query = "insert into customer(id, fullName, phoneNumber, nationality, gender, idProof, address, checkInDate, roomNo, bedType, roomType, smokingRoom, pricePerDay) values("+id+", '"+name+"', '"+phoneNumber+"','"+gender+"', '"+nationality+"', '"+idProof+"', '"+address+"', '"+date+"', '"+roomNumber+"', '"+bedType+"', '"+room+"', '"+smoking+"', '"+roomPrice+"')";
                InsertUpdateDelete.setData(Query, "Customer Check In Success");
                setVisible(false);
                new CheckIn().setVisible(true);
                
            }
            
        }
        catch(Exception e)
        {
              JOptionPane.showMessageDialog(null, "Check In Failed");
        } 
    }//GEN-LAST:event_checkInButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JTextField IDProofField;
    private javax.swing.JComboBox<String> Nationality;
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel backButton;
    private javax.swing.JLabel baseLayout;
    private javax.swing.JComboBox<String> bedTypeField;
    private javax.swing.JLabel checkInButton;
    private javax.swing.JTextField dateField;
    private javax.swing.JLabel dateLayout;
    private javax.swing.JTextField fullNameField;
    private javax.swing.JLabel header;
    private javax.swing.JLabel identityLayout;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JTextField priceField;
    private javax.swing.JLabel roomLayout;
    private javax.swing.JComboBox<String> roomNumberField;
    private javax.swing.JComboBox<String> roomTypeField;
    private javax.swing.JComboBox<String> smokingRoomField;
    // End of variables declaration//GEN-END:variables
}
