import Project.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.BorderFactory;
import javax.swing.border.Border;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Utari Dyani
 */
public class CheckIn extends javax.swing.JFrame {

    /**
     * Creates new form CheckIn
     */
    public CheckIn() {
        initComponents();
        
        //mengatur tanggal check in menjadi tanggal hari ini
        dateField.setEditable(true);
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        Calendar cal = Calendar.getInstance();
        dateField.setText(format.format(cal.getTime()));
        dateField.setFont(new Font("Segoe UI Historic", Font.PLAIN, 30));
    }
    
    //deklarasi objek
    String bed;
    String roomType;
    String roomNo;
    String price;
    String roomStatus;
    
    //method untuk menyeleksi kamar sesuai dengan keinginan customer
    public void roomDetails(){
        roomNumberField.removeAllItems();
        priceField.setText("");
        bed = (String)bedTypeField.getSelectedItem();
        roomType = (String)roomTypeField.getSelectedItem();
        roomStatus = "Available";
        
        try
        {
            ResultSet rs = Select.getData("select *from room where bed = '"+bed+"' and roomType='"+roomType+"' and Status = 'Available'");
            while(rs.next())
            {
                roomNumberField.addItem(rs.getString(1));
                priceField.setText(rs.getString(4));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    //Method untuk Memfilter Kolom hanya Bisa Diisi Huruf
    public void filterHuruf(KeyEvent a){
        if(Character.isDigit(a.getKeyChar())){
            a.consume();
            //Tampilan peringatan jika user memasukkan data berupa angka atau yang lain
            JOptionPane.showMessageDialog(null, "Alphabet or Character Only!", "Warning!", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    //Method Untuk Validasi Inputan User Berupa Angka
    public void filterAngka (KeyEvent b){
        if(Character.isAlphabetic(b.getKeyChar())){
            b.consume();
            //Tampilan peringatan jika user memasukkan karakter yang bukan angka
            JOptionPane.showMessageDialog(null, "Numeric Only!", "Warning!", JOptionPane.WARNING_MESSAGE);       
        }
    }
    
    //method untuk memfilter spasi
    public void filterSpace (KeyEvent c){
        if(Character.isWhitespace(c.getKeyChar())){
            c.consume();
            //Tampilan peringatan jika user menginputkan spasi
            JOptionPane.showMessageDialog(null, "No Spacing", "Warning!", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gender = new javax.swing.JComboBox<>();
        roomTypeField = new javax.swing.JComboBox<>();
        Nationality = new javax.swing.JComboBox<>();
        bedTypeField = new javax.swing.JComboBox<>();
        priceField = new javax.swing.JTextField();
        roomNumberField = new javax.swing.JComboBox<>();
        dateField = new javax.swing.JTextField();
        checkInButton = new javax.swing.JLabel();
        backButton = new javax.swing.JLabel();
        IDProofField = new javax.swing.JTextField();
        phoneNumberField = new javax.swing.JTextField();
        fullNameField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1366, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Gender.setBackground(new java.awt.Color(242, 218, 218));
        Gender.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        Gender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 218, 218), 7));
        Gender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 450, 320, -1));

        roomTypeField.setBackground(new java.awt.Color(242, 218, 218));
        roomTypeField.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        roomTypeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIP", "VVIP", "Connected", "AC", "Non-AC" }));
        roomTypeField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 218, 218), 5));
        roomTypeField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        roomTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomTypeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(roomTypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 310, 440, 40));

        Nationality.setBackground(new java.awt.Color(242, 218, 218));
        Nationality.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        Nationality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indonesia", "Malaysia", "Singapura", "Thailand", "Brunei", "Russia" }));
        Nationality.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 218, 218), 7));
        Nationality.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 320, -1));

        bedTypeField.setBackground(new java.awt.Color(242, 218, 218));
        bedTypeField.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        bedTypeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));
        bedTypeField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 218, 218), 5));
        bedTypeField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bedTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bedTypeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(bedTypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, 440, 40));

        priceField.setBackground(new java.awt.Color(242, 218, 218));
        priceField.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        getContentPane().add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 480, 440, 40));

        roomNumberField.setBackground(new java.awt.Color(242, 218, 218));
        roomNumberField.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        roomNumberField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1001", "1002", "1003", "1004", "1005", "1006", "1007", "1008", "1009", "1010", "1011", "1012", "1013", "1014", "1015" }));
        roomNumberField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 218, 218), 5));
        roomNumberField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        roomNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNumberFieldActionPerformed(evt);
            }
        });
        getContentPane().add(roomNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 440, 40));

        dateField.setBackground(new java.awt.Color(242, 218, 218));
        dateField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateFieldMouseClicked(evt);
            }
        });
        dateField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dateFieldKeyTyped(evt);
            }
        });
        getContentPane().add(dateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 620, 420, 60));

        checkInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/CheckIn_Button.png"))); // NOI18N
        checkInButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkInButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkInButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                checkInButtonMouseExited(evt);
            }
        });
        getContentPane().add(checkInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 540, -1, -1));

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/CheckIn_BackButton.png"))); // NOI18N
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backButtonMouseExited(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1335, 0, -1, -1));

        IDProofField.setBackground(new java.awt.Color(242, 218, 218));
        IDProofField.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        IDProofField.setBorder(null);
        IDProofField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDProofFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDProofFieldFocusLost(evt);
            }
        });
        IDProofField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IDProofFieldKeyTyped(evt);
            }
        });
        getContentPane().add(IDProofField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 640, 20));

        phoneNumberField.setBackground(new java.awt.Color(242, 218, 218));
        phoneNumberField.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        phoneNumberField.setBorder(null);
        phoneNumberField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneNumberFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneNumberFieldFocusLost(evt);
            }
        });
        phoneNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNumberFieldKeyTyped(evt);
            }
        });
        getContentPane().add(phoneNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 640, 20));

        fullNameField.setBackground(new java.awt.Color(242, 218, 218));
        fullNameField.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        fullNameField.setBorder(null);
        fullNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fullNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fullNameFieldFocusLost(evt);
            }
        });
        fullNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fullNameFieldKeyTyped(evt);
            }
        });
        getContentPane().add(fullNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 640, 30));

        addressField.setBackground(new java.awt.Color(242, 218, 218));
        addressField.setFont(new java.awt.Font("Segoe UI Historic", 0, 20)); // NOI18N
        addressField.setBorder(null);
        addressField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressFieldFocusLost(evt);
            }
        });
        getContentPane().add(addressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 640, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/CheckIn Layout.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setBounds(0, 0, 1372, 785);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setExtendedState(CheckIn.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void phoneNumberFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumberFieldKeyTyped
        filterAngka(evt);
        filterSpace(evt);
    }//GEN-LAST:event_phoneNumberFieldKeyTyped

    private void roomTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomTypeFieldActionPerformed
        roomDetails();
    }//GEN-LAST:event_roomTypeFieldActionPerformed

    private void roomNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNumberFieldActionPerformed
        roomNo=(String)roomNumberField.getSelectedItem();
        try
        {
            ResultSet rs=Select.getData("select *from room where roomNumber='"+roomNo+"'");
            while(rs.next())
            {
                priceField.setText(rs.getString(4));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_roomNumberFieldActionPerformed

    private void checkInButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkInButtonMouseEntered
        checkInButton.setSize(135, 42);
    }//GEN-LAST:event_checkInButtonMouseEntered

    private void checkInButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkInButtonMouseExited
        checkInButton.setSize(131, 38);
    }//GEN-LAST:event_checkInButtonMouseExited

    private void checkInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkInButtonMouseClicked
        //pendeklarasian objek
        int id = 1;
        String name = fullNameField.getText();
        String idProof = IDProofField.getText();
        String phoneNumber = phoneNumberField.getText();
        String address = addressField.getText();
        String nationality =(String)Nationality.getSelectedItem();
        String gender = (String)Gender.getSelectedItem();
        String date = dateField.getText();
        String bedType = (String)bedTypeField.getSelectedItem();
        String room = (String)roomTypeField.getSelectedItem();
        String roomNumber = (String)roomNumberField.getSelectedItem();
        String roomPrice = priceField.getText();
        String Query = "select max(id) from customer";
        if(name.isEmpty()||idProof.isEmpty()||phoneNumber.isEmpty()||address.isEmpty()||nationality.isEmpty()||gender.isEmpty()||date.isEmpty()||bedType.isEmpty()||room.isEmpty()||roomNumber.isEmpty()||roomPrice.isEmpty()){
            JOptionPane.showMessageDialog(null, "All Field is Required", "Error", JOptionPane.ERROR_MESSAGE);
        }
        try
        {
            ResultSet rs = Select.getData(Query);
            while(rs.next())
                id=rs.getInt(1);
            id=id+1;
            
            if(!roomPrice.equals(""))
            {
                Query = "update room set status = 'Booked' where roomNumber = '"+roomNumber+"'";
                InsertUpdateDelete.setData(Query, "");
                Query = "insert into customer(id, fullName, phoneNumber, nationality, gender, idproof, address, checkInDate, roomNo, bedType, roomType, pricePerDay) values("+id+", '"+name+"', '"+phoneNumber+"','"+nationality+"', '"+gender+"', '"+idProof+"', '"+address+"', '"+date+"', '"+roomNumber+"', '"+bedType+"', '"+room+"', '"+roomPrice+"')";
                InsertUpdateDelete.setData(Query, "Customer Check In Success");
                setVisible(false);
                new CheckIn().setVisible(true);
                
            }
            
        }
        catch(Exception e)
        {
              JOptionPane.showMessageDialog(null, "Check In Failed");
        } 
    }//GEN-LAST:event_checkInButtonMouseClicked

    private void IDProofFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDProofFieldKeyTyped
        filterAngka(evt);
        filterSpace(evt);
    }//GEN-LAST:event_IDProofFieldKeyTyped

    private void fullNameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fullNameFieldKeyTyped
        filterHuruf(evt);
    }//GEN-LAST:event_fullNameFieldKeyTyped

    private void fullNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fullNameFieldFocusGained
        // TODO add your handling code here:
        String fullName = fullNameField.getText();

        if(fullName.trim().toLowerCase().equals(("full name"))){
            fullNameField.setText("");
            fullNameField.setForeground(Color.black);
        }
    }//GEN-LAST:event_fullNameFieldFocusGained

    private void fullNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fullNameFieldFocusLost
        // TODO add your handling code here:
        String fullName = fullNameField.getText();

        if(fullName.trim().toLowerCase().equals(("Full Name"))||fullName.trim().toLowerCase().equals("")){
            fullNameField.setText("Full Name");
            fullNameField.setForeground(new Color(153,153,153));
        }
        fullNameField.setBorder(null);
    }//GEN-LAST:event_fullNameFieldFocusLost

    private void IDProofFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDProofFieldFocusGained
        // TODO add your handling code here:
        String IDProof = IDProofField.getText();

        if(IDProof.trim().toLowerCase().equals(("id"))){
            IDProofField.setText("");
            IDProofField.setForeground(Color.black);
        }
    }//GEN-LAST:event_IDProofFieldFocusGained

    private void IDProofFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDProofFieldFocusLost
        // TODO add your handling code here:
        String IDProof = IDProofField.getText();

        if(IDProof.trim().toLowerCase().equals(("ID"))||IDProof.trim().toLowerCase().equals("")){
            IDProofField.setText("ID");
            IDProofField.setForeground(new Color(153,153,153));
        }
        IDProofField.setBorder(null);
    }//GEN-LAST:event_IDProofFieldFocusLost

    private void phoneNumberFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneNumberFieldFocusGained
        // TODO add your handling code here:
        String PhoneNumber = phoneNumberField.getText();

        if(PhoneNumber.trim().toLowerCase().equals(("phone number"))){
            phoneNumberField.setText("");
            phoneNumberField.setForeground(Color.black);
        }
    }//GEN-LAST:event_phoneNumberFieldFocusGained

    private void phoneNumberFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneNumberFieldFocusLost
        // TODO add your handling code here:
        String PhoneNumber = phoneNumberField.getText();

        if(PhoneNumber.trim().toLowerCase().equals(("Phone Number"))||PhoneNumber.trim().toLowerCase().equals("")){
            phoneNumberField.setText("Phone Number");
            phoneNumberField.setForeground(new Color(153,153,153));
        }
        phoneNumberField.setBorder(null);
    }//GEN-LAST:event_phoneNumberFieldFocusLost

    private void addressFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFieldFocusGained
        // TODO add your handling code here:
        String address = addressField.getText();

        if(address.trim().toLowerCase().equals(("address"))){
            addressField.setText("");
            addressField.setForeground(Color.black);
        }
    }//GEN-LAST:event_addressFieldFocusGained

    private void addressFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFieldFocusLost
        // TODO add your handling code here:
        String address = addressField.getText();

        if(address.trim().toLowerCase().equals(("Address"))||address.trim().toLowerCase().equals("")){
            addressField.setText("Address");
            addressField.setForeground(new Color(153,153,153));
        }
        addressField.setBorder(null);
    }//GEN-LAST:event_addressFieldFocusLost

    private void dateFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateFieldKeyTyped
        // TODO add your handling code here:
        filterAngka(evt);
        filterSpace(evt);
    }//GEN-LAST:event_dateFieldKeyTyped

    private void dateFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateFieldMouseClicked
        // TODO add your handling code here:
        dateField.setText("");
    }//GEN-LAST:event_dateFieldMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        dispose();
        Menu menu = new Menu();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
    }//GEN-LAST:event_backButtonMouseClicked

    private void backButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseEntered
        // TODO add your handling code here:
        Border IconBorder = BorderFactory.createMatteBorder(1,1,1,1, new Color(255, 225, 255));
        backButton.setBorder(IconBorder);
        backButton.setForeground(new Color(255, 225, 255));
    }//GEN-LAST:event_backButtonMouseEntered

    private void backButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseExited
        // TODO add your handling code here:
        Border IconBorder = BorderFactory.createMatteBorder(0,0,0,0, Color.white);
        backButton.setBorder(IconBorder);
        backButton.setForeground(Color.white);
    }//GEN-LAST:event_backButtonMouseExited

    private void bedTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bedTypeFieldActionPerformed
        // TODO add your handling code here:
        roomDetails();
    }//GEN-LAST:event_bedTypeFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JTextField IDProofField;
    private javax.swing.JComboBox<String> Nationality;
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel backButton;
    private javax.swing.JComboBox<String> bedTypeField;
    private javax.swing.JLabel checkInButton;
    private javax.swing.JTextField dateField;
    private javax.swing.JTextField fullNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JTextField priceField;
    private javax.swing.JComboBox<String> roomNumberField;
    private javax.swing.JComboBox<String> roomTypeField;
    // End of variables declaration//GEN-END:variables
}
