
import Project.InsertUpdateDelete;
import Project.Select;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ABEL
 */
public class ManageRoom extends javax.swing.JFrame {

    /**
     * Creates new form ManageRoom
     */
    public ManageRoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RoomType = new javax.swing.JComboBox<>();
        Bed = new javax.swing.JComboBox<>();
        Status = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        AddButton = new javax.swing.JLabel();
        RoomNumber = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        Back = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIP", "VVIP", "Connected", "AC", "Non-AC" }));
        getContentPane().add(RoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 340, 350, 30));

        Bed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));
        getContentPane().add(Bed, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 420, 350, 30));

        Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Booked", "Under Maintenance" }));
        getContentPane().add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 590, 350, 30));

        jScrollPane1.setBackground(new java.awt.Color(229, 155, 132));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(229, 155, 132)));
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        jTable1.setBackground(new java.awt.Color(229, 155, 132));
        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Number", "Room Type", "Bed", "Price", "Status"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setSelectionBackground(new java.awt.Color(229, 155, 132));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 150, 790, 560));

        AddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Add Button.png"))); // NOI18N
        AddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddButtonMouseExited(evt);
            }
        });
        getContentPane().add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 650, 190, -1));

        RoomNumber.setBackground(new java.awt.Color(229, 155, 132));
        RoomNumber.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        RoomNumber.setBorder(null);
        getContentPane().add(RoomNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(927, 250, 340, -1));

        Price.setBackground(new java.awt.Color(229, 155, 132));
        Price.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        Price.setBorder(null);
        getContentPane().add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(927, 500, 340, -1));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Back Button.png"))); // NOI18N
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 0, 30, 30));

        jLabel1.setBackground(new java.awt.Color(229, 155, 132));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Manage Room Frame.png"))); // NOI18N
        jLabel1.setRequestFocusEnabled(false);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseEntered
        // TODO add your handling code here:
        Border IconBorder = BorderFactory.createMatteBorder(3,3,3,3, new Color(229, 155, 132));
        AddButton.setBorder(IconBorder);
        AddButton.setForeground(new Color(229, 155, 132));
    }//GEN-LAST:event_AddButtonMouseEntered

    private void AddButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseExited
        // TODO add your handling code here:
        Border IconBorder = BorderFactory.createMatteBorder(0,0,0,0, Color.white);
        AddButton.setBorder(IconBorder);
        AddButton.setForeground(Color.white);
    }//GEN-LAST:event_AddButtonMouseExited

    private void AddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseClicked
        // TODO add your handling code here:
        String RoomNum = RoomNumber.getText();
        String RoomTypes = (String)RoomType.getSelectedItem();
        String BedType = (String)Bed.getSelectedItem();
        String RoomPrice = Price.getText();
        String RoomStatus = (String)Status.getSelectedItem();
        if(RoomNum.equals("")||RoomType.equals("")||BedType.equals("")||RoomPrice.equals("")||RoomStatus.equals("")){
            JOptionPane.showMessageDialog(null, "All Field is Required", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            String Query;
            Query = "insert into room values('"+RoomNum+"', '"+RoomTypes+"', '"+BedType+"', '"+RoomPrice+"', '"+RoomStatus+"')";
            InsertUpdateDelete.setData(Query, "Inserted Succcesfully");
            setVisible(false);
            new ManageRoom().setVisible(true);
        }
    }//GEN-LAST:event_AddButtonMouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        // TODO add your handling code here:
        dispose();
        Menu menu = new Menu();
        // Digunakan untuk meletakkan form register ditengah
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
    }//GEN-LAST:event_BackMouseClicked

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseEntered
        // TODO add your handling code here:
        Border IconBorder = BorderFactory.createMatteBorder(1,1,1,1, new Color(255, 225, 255));
        Back.setBorder(IconBorder);
        Back.setForeground(new Color(255, 225, 255));
    }//GEN-LAST:event_BackMouseEntered

    private void BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseExited
        // TODO add your handling code here:
        Border IconBorder = BorderFactory.createMatteBorder(0,0,0,0, Color.white);
        Back.setBorder(IconBorder);
        Back.setForeground(Color.white);
    }//GEN-LAST:event_BackMouseExited

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ResultSet rs=Select.getData("select *from room");
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        try
        {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4),rs.getString(5)});
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Insertion Failed");
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddButton;
    private javax.swing.JLabel Back;
    private javax.swing.JComboBox<String> Bed;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField RoomNumber;
    private javax.swing.JComboBox<String> RoomType;
    private javax.swing.JComboBox<String> Status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
