/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import Project.InsertUpdateDelete;
/**
 *
 * @author ABEL
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form Sign_Up
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        NameSignUp = new javax.swing.JTextField();
        UsernameSignUp = new javax.swing.JTextField();
        EmailSignUp = new javax.swing.JTextField();
        PasswordSignUp = new javax.swing.JPasswordField();
        AnswerQuestion = new javax.swing.JTextField();
        AddressSignUp = new javax.swing.JTextField();
        Back = new javax.swing.JLabel();
        SignUpButton = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameSignUp.setBackground(new java.awt.Color(242, 218, 218));
        NameSignUp.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        NameSignUp.setBorder(null);
        NameSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        NameSignUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NameSignUpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NameSignUpFocusLost(evt);
            }
        });
        getContentPane().add(NameSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 710, 30));

        UsernameSignUp.setBackground(new java.awt.Color(242, 218, 218));
        UsernameSignUp.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        UsernameSignUp.setBorder(null);
        UsernameSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        UsernameSignUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameSignUpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameSignUpFocusLost(evt);
            }
        });
        getContentPane().add(UsernameSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 710, 30));

        EmailSignUp.setBackground(new java.awt.Color(242, 218, 218));
        EmailSignUp.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        EmailSignUp.setBorder(null);
        EmailSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        EmailSignUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailSignUpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailSignUpFocusLost(evt);
            }
        });
        getContentPane().add(EmailSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 710, 30));

        PasswordSignUp.setBackground(new java.awt.Color(242, 218, 218));
        PasswordSignUp.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        PasswordSignUp.setBorder(null);
        PasswordSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        PasswordSignUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordSignUpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordSignUpFocusLost(evt);
            }
        });
        getContentPane().add(PasswordSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 710, 30));

        AnswerQuestion.setBackground(new java.awt.Color(242, 218, 218));
        AnswerQuestion.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        AnswerQuestion.setBorder(null);
        AnswerQuestion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        AnswerQuestion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AnswerQuestionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AnswerQuestionFocusLost(evt);
            }
        });
        AnswerQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerQuestionActionPerformed(evt);
            }
        });
        getContentPane().add(AnswerQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 710, 30));

        AddressSignUp.setBackground(new java.awt.Color(242, 218, 218));
        AddressSignUp.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        AddressSignUp.setBorder(null);
        AddressSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        AddressSignUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AddressSignUpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AddressSignUpFocusLost(evt);
            }
        });
        getContentPane().add(AddressSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, 710, 30));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Back Button.png"))); // NOI18N
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 0, 30, 30));

        SignUpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/SignUp Button.png"))); // NOI18N
        SignUpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignUpButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignUpButtonMouseExited(evt);
            }
        });
        getContentPane().add(SignUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 640, 160, 60));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What's your favourite food?", "What\"s your first pet?", "What's is your first console?", "What's your name?" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 255)));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 600, 240, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/SignUp.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>                        

    private void AnswerQuestionActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void NameSignUpFocusGained(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
        String nameValue = NameSignUp.getText();

        if(nameValue.trim().toLowerCase().equals(("name"))){
            NameSignUp.setText("");
            NameSignUp.setForeground(Color.black);
        }
    }                                      

    private void NameSignUpFocusLost(java.awt.event.FocusEvent evt) {                                     
        // TODO add your handling code here:
         String nameValue = NameSignUp.getText();

        if(nameValue.trim().toLowerCase().equals(("name"))||nameValue.trim().toLowerCase().equals("")){
            NameSignUp.setText("Name");
            NameSignUp.setForeground(new Color(153,153,153));
        }
        NameSignUp.setBorder(null);  
    }                                    

    private void UsernameSignUpFocusGained(java.awt.event.FocusEvent evt) {                                           
        // TODO add your handling code here:
        String usernameValue = UsernameSignUp.getText();

        if(usernameValue.trim().toLowerCase().equals(("username"))){
            UsernameSignUp.setText("");
            UsernameSignUp.setForeground(Color.black);
        }
    }                                          

    private void UsernameSignUpFocusLost(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
        String usernameValue = UsernameSignUp.getText();

        if(usernameValue.trim().toLowerCase().equals(("username"))||usernameValue.trim().toLowerCase().equals("")){
            UsernameSignUp.setText("Username");
            UsernameSignUp.setForeground(new Color(153,153,153));
        }
        UsernameSignUp.setBorder(null);
    }                                        

    private void EmailSignUpFocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
        String emailValue = EmailSignUp.getText();
        
        if(emailValue.trim().toLowerCase().equals("email")){
            EmailSignUp.setText("");
            EmailSignUp.setForeground(Color.black);
        }
    }                                       

    private void EmailSignUpFocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
         String emailValue = EmailSignUp.getText();
        
        if(emailValue.trim().toLowerCase().equals("address")||emailValue.trim().toLowerCase().equals("")){
            EmailSignUp.setText("Email");
            EmailSignUp.setForeground(new Color(153, 153, 153));
        }
        EmailSignUp.setBorder(null);
    }                                     

    private void PasswordSignUpFocusGained(java.awt.event.FocusEvent evt) {                                           
        // TODO add your handling code here:
        String passwordValue = String.valueOf(PasswordSignUp.getPassword());

        if(passwordValue.trim().toLowerCase().equals(("password"))){
            PasswordSignUp.setText("");
            PasswordSignUp.setForeground(Color.black);
        }     
    }                                          

    private void PasswordSignUpFocusLost(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
        String passwordValue = String.valueOf(PasswordSignUp.getPassword());

        if(passwordValue.trim().toLowerCase().equals(("password"))||passwordValue.trim().toLowerCase().equals("")){
            PasswordSignUp.setText("Password");
            PasswordSignUp.setForeground(new Color(153,153,153));
        }
        PasswordSignUp.setBorder(null);
    }                                        

    private void AnswerQuestionFocusGained(java.awt.event.FocusEvent evt) {                                           
        // TODO add your handling code here:
        String AnswerValue = AnswerQuestion.getText();
        
        if(AnswerValue.trim().toLowerCase().equals(("answer"))){
            AnswerQuestion.setText("");
            AnswerQuestion.setForeground(Color.black);
        }
    }                                          

    private void AnswerQuestionFocusLost(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
        String AnswerValue = AnswerQuestion.getText();
        
        if(AnswerValue.trim().toLowerCase().equals(("answer"))||AnswerValue.trim().toLowerCase().equals("")){
            AnswerQuestion.setText("Answer");
            AnswerQuestion.setForeground(new Color(153,153,153));
        }
        AnswerQuestion.setBorder(null); 
    }                                        

    private void AddressSignUpFocusGained(java.awt.event.FocusEvent evt) {                                          
        // TODO add your handling code here:
        String AddressValue = AddressSignUp.getText();
        
        if(AddressValue.trim().toLowerCase().equals("address")){
            AddressSignUp.setText("");
            AddressSignUp.setForeground(Color.black);
        }
    }                                         

    private void AddressSignUpFocusLost(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
         String AddressValue = AddressSignUp.getText();
        
        if(AddressValue.trim().toLowerCase().equals("address")||AddressValue.trim().toLowerCase().equals("")){
            AddressSignUp.setText("Address");
            AddressSignUp.setForeground(new Color(153, 153, 153));
        }
        AddressSignUp.setBorder(null);
    }                                       

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
        dispose();
        LandingPage Land = new LandingPage();
        Land.setLocationRelativeTo(null);
        Land.setVisible(true);
    }                                 

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
        Border IconBorder = BorderFactory.createMatteBorder(1,1,1,1, new Color(255, 225, 255));
        Back.setBorder(IconBorder);
        Back.setForeground(new Color(255, 255, 255));
    }                                 

    private void BackMouseExited(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
        Border IconBorder = BorderFactory.createMatteBorder(0,0,0,0, Color.white);
        Back.setBorder(IconBorder);
        Back.setForeground(Color.white);
    }                                

    private void SignUpButtonMouseExited(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        Border IconBorder = BorderFactory.createMatteBorder(0,0,0,0, Color.white);
        SignUpButton.setBorder(IconBorder);
        SignUpButton.setForeground(Color.white);
    }                                        

    private void SignUpButtonMouseEntered(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        Border IconBorder = BorderFactory.createMatteBorder(3,3,3,3, new Color(219,123,93));
        SignUpButton.setBorder(IconBorder);
        SignUpButton.setForeground(new Color(219,123,93));
    }                                         

    private void SignUpButtonMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        String name = NameSignUp.getText();
        String username = UsernameSignUp.getText();
        String email = EmailSignUp.getText();
        String password = String.valueOf(PasswordSignUp.getPassword());
        String answer = AnswerQuestion.getText();
        String address = AddressSignUp.getText();
        String securityQuestion = (String)jComboBox1.getSelectedItem();
        if(name.equals("")||username.equals("")||email.equals("")||password.equals("")||answer.equals("")||address.equals("")||securityQuestion.equals("")){
            JOptionPane.showMessageDialog(null, "All Field is Required", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            String Query;
            Query="insert into admin values('"+name+"', '"+username+"', '"+email+"', '"+password+"', '"+answer+"', '"+address+"', '"+securityQuestion+"', 'false')";
            InsertUpdateDelete.setData(Query, "Registered Succcesfully");
            setVisible(false);
            new SignUp().setVisible(true);
        }
    }                                         
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField AddressSignUp;
    private javax.swing.JTextField AnswerQuestion;
    private javax.swing.JLabel Back;
    private javax.swing.JTextField EmailSignUp;
    private javax.swing.JTextField NameSignUp;
    private javax.swing.JPasswordField PasswordSignUp;
    private javax.swing.JLabel SignUpButton;
    private javax.swing.JTextField UsernameSignUp;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   
}
