
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ABEL
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NameSignUp = new javax.swing.JTextField();
        PasswordSignUp = new javax.swing.JPasswordField();
        UsernameSignUp = new javax.swing.JTextField();
        PasswordCheckSignUp = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        AnswerQuestion = new javax.swing.JTextField();
        AddressSignUp = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Close.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1326, 11, 30, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Minimize.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 11, 30, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sign Up");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 90, -1));

        NameLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameLabel.setText("Name");
        NameLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 40, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 60, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 60, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Re-type Password");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 100, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Security Question");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 100, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Answer");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 50, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 50, -1));

        NameSignUp.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        NameSignUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NameSignUpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NameSignUpFocusLost(evt);
            }
        });
        NameSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(NameSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 340, -1));

        PasswordSignUp.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        PasswordSignUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordSignUpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordSignUpFocusLost(evt);
            }
        });
        PasswordSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 340, -1));

        UsernameSignUp.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        UsernameSignUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameSignUpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameSignUpFocusLost(evt);
            }
        });
        getContentPane().add(UsernameSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 340, -1));

        PasswordCheckSignUp.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        PasswordCheckSignUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordCheckSignUpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordCheckSignUpFocusLost(evt);
            }
        });
        PasswordCheckSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordCheckSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordCheckSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 340, -1));

        jComboBox1.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What's your favourite food?", "What's was your first bike?", "What's the name of the town or city where you were born?", "What's your favourite song?", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 340, -1));

        AnswerQuestion.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        AnswerQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerQuestionActionPerformed(evt);
            }
        });
        getContentPane().add(AnswerQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 340, -1));

        AddressSignUp.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        getContentPane().add(AddressSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 340, -1));

        jButton3.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Login");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, -1, -1));

        jButton4.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Sign Up");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 116, -1));

        jButton5.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Forgot Password?");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 490, 130, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/signup.PNG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordSignUpActionPerformed

    private void NameSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameSignUpActionPerformed

    private void AnswerQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnswerQuestionActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton2MouseClicked

    private void PasswordSignUpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordSignUpFocusGained
        // TODO add your handling code here:
        String passwordValue = String.valueOf(PasswordSignUp.getPassword());

        if(passwordValue.trim().toLowerCase().equals(("password"))){
            PasswordSignUp.setText("");
            PasswordSignUp.setForeground(Color.black);
        }
        Border LampBorder = BorderFactory.createMatteBorder(2,2,2,2, Color.white);
        PasswordSignUp.setBorder(LampBorder);                               
    }//GEN-LAST:event_PasswordSignUpFocusGained

    private void PasswordSignUpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordSignUpFocusLost
        // TODO add your handling code here:
        String passwordValue = String.valueOf(PasswordSignUp.getPassword());

        if(passwordValue.trim().toLowerCase().equals(("password"))||passwordValue.trim().toLowerCase().equals("")){
            PasswordSignUp.setText("Password");
            PasswordSignUp.setForeground(new Color(153,153,153));
        }
        PasswordSignUp.setBorder(null);
    }//GEN-LAST:event_PasswordSignUpFocusLost

    private void UsernameSignUpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameSignUpFocusGained
        // TODO add your handling code here:
        String usernameValue = UsernameSignUp.getText();

        if(usernameValue.trim().toLowerCase().equals(("username"))){
            UsernameSignUp.setText("");
            UsernameSignUp.setForeground(Color.black);
        }
        Border LampBorder = BorderFactory.createMatteBorder(2,2,2,2, Color.white);
        UsernameSignUp.setBorder(LampBorder);   
    }//GEN-LAST:event_UsernameSignUpFocusGained

    private void UsernameSignUpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameSignUpFocusLost
        // TODO add your handling code here:
        String usernameValue = UsernameSignUp.getText();

        if(usernameValue.trim().toLowerCase().equals(("username"))||usernameValue.trim().toLowerCase().equals("")){
            UsernameSignUp.setText("Username");
            UsernameSignUp.setForeground(new Color(153,153,153));
        }
        UsernameSignUp.setBorder(null);
    }//GEN-LAST:event_UsernameSignUpFocusLost

    private void NameSignUpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameSignUpFocusGained
        // TODO add your handling code here:
        String nameValue = NameSignUp.getText();

        if(nameValue.trim().toLowerCase().equals(("name"))){
            NameSignUp.setText("");
            NameSignUp.setForeground(Color.black);
        }
        Border LampBorder = BorderFactory.createMatteBorder(2,2,2,2, Color.white);
        NameSignUp.setBorder(LampBorder);  
    }//GEN-LAST:event_NameSignUpFocusGained

    private void NameSignUpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameSignUpFocusLost
        // TODO add your handling code here:
        String nameValue = NameSignUp.getText();

        if(nameValue.trim().toLowerCase().equals(("name"))||nameValue.trim().toLowerCase().equals("")){
            NameSignUp.setText("Name");
            NameSignUp.setForeground(new Color(153,153,153));
        }
        NameSignUp.setBorder(null);  
    }//GEN-LAST:event_NameSignUpFocusLost

    private void PasswordCheckSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordCheckSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordCheckSignUpActionPerformed

    private void PasswordCheckSignUpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordCheckSignUpFocusGained
        // TODO add your handling code here:
        String passwordValue = String.valueOf(PasswordCheckSignUp.getPassword());

        if(passwordValue.trim().toLowerCase().equals(("password"))){
            PasswordCheckSignUp.setText("");
            PasswordCheckSignUp.setForeground(Color.black);
        }
        Border LampBorder = BorderFactory.createMatteBorder(2,2,2,2, Color.white);
        PasswordCheckSignUp.setBorder(LampBorder);
    }//GEN-LAST:event_PasswordCheckSignUpFocusGained

    private void PasswordCheckSignUpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordCheckSignUpFocusLost
        // TODO add your handling code here:
        String passwordValue = String.valueOf(PasswordCheckSignUp.getPassword());

        if(passwordValue.trim().toLowerCase().equals(("password"))||passwordValue.trim().toLowerCase().equals("")){
            PasswordCheckSignUp.setText("");
            PasswordCheckSignUp.setForeground(new Color(153,153,153));
        }
        PasswordCheckSignUp.setBorder(null);
    }//GEN-LAST:event_PasswordCheckSignUpFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressSignUp;
    private javax.swing.JTextField AnswerQuestion;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameSignUp;
    private javax.swing.JPasswordField PasswordCheckSignUp;
    private javax.swing.JPasswordField PasswordSignUp;
    private javax.swing.JTextField UsernameSignUp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
